server:
  servlet:
    context-path: /prueba-inditex-prices

spring:
  application:
    name: prueba-inditex-prices
  datasource:
    url: jdbc:h2:mem:pricesdb
    driverClassName: org.h2.Driver
    username: username
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    encoding: UTF-8



logbook:
  format:
    style: http

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

