DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    BRAND_ID INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST BIGINT PRIMARY KEY,
    PRODUCT_ID INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE NUMERIC(20, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL
);

CREATE INDEX IDX_BRAND_PRODUCT ON PRICES (BRAND_ID, PRODUCT_ID);