DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    BRAND_ID INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE NUMERIC(20, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL
);

CREATE INDEX idx_brand_product_date ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);